nats-io/nats.rb

lib/nats/client.rb
lib/nats/server/const.rb
spec/client_cluster_reconnect_spec.rb

follow the go-nats client behavior and respect when servers should not be
removed on failed connectes
See issue #87

Never remove servers when configured as such

---

lib/nats/client.rb

It used to be the case that EventMachine would not throw warnings and calling `EM.epoll` or `EM.kqueue` would be a no-op in case there was no support for it on the platform.
https://github.com/eventmachine/eventmachine/blob/master/docs/old/EPOLL#L42
Due to changes in EventMachine 1.0.8 (https://github.com/eventmachine/eventmachine/commit/9af94064e1f05b373145ba0c3cac41daa9daf369),
now warnings like these are thrown when using the client:
```
warning: epoll is not supported on this platform
warning: kqueue is not supported on this platform
```
This patch silences these warnings once again to get the old behavior. Fixes #89

Silence warning when setting epoll or kqueue by detecting it first

---

lib/nats/client.rb

@buf and @ssl were not initialized in some cases such as when options did not have an options[:ssl] value.

Initialize variables @buf and @ssl.

---

lib/nats/client.rb
spec/client/reconnect_spec.rb

If there is an error connecting the first time, reconnecting is false and outstanding subs are never added.
Always add subscriptions whether you are successfully connecting for the first time or not.

Apply subs whenever connect is completed

---

lib/nats/client.rb
spec/client/client_spec.rb
spec/client/sub_timeouts_spec.rb

Follow up from [previous commit](https://github.com/nats-io/ruby-nats/commit/3f3efc6bc41cc483f2d90cb9d401ba4aa3e727d3), where unnecessary `SUB` commands can be sent to the server because of being buffered before connecting. In order to avoid sending extra `SUB` commands, we detect and remove them once reaching `connection_completed`. 
/cc @derekcollison

Remove extra pending SUBs command which can appear when connecting

---

lib/nats/client.rb
nats.gemspec

Added a `nats/version.rb` file to load it in the gemspec, though also has to be added into the files in the gemspec and required by the client too in order to send to send the version to the server on connect...

Add version.rb file to list in gemspec and require in client

---

README.md

missing paren in cluster example

---

Gemfile
Gemfile.lock
nats.gemspec
spec/client/attack_spec.rb
spec/client/auth_spec.rb
spec/client/client_cluster_config_spec.rb
spec/client/client_cluster_reconnect_spec.rb
spec/client/client_config_spec.rb
spec/client/client_spec.rb
spec/client/reconnect_spec.rb
spec/server/monitor_spec.rb
spec/server/server_ping_spec.rb
spec/server/ssl_spec.rb
spec/spec_helper.rb

A number of tests flapping when upgrading eventmachine version,
so spec is revised a bit to accomodate to latest behavior.
Fixes #103

Bump eventmachine version, update specs to reduce flappers

---

Gemfile.lock
lib/nats/version.rb
nats.gemspec

These are not needed anymore for the client so taking them out.
Fixes #116

Remove server deps from client

---

lib/nats/client.rb

A user worried that Nats wasn't working under JRuby because of this warning. 
https://github.com/nats-io/ruby-nats/issues/72#issuecomment-233789670
https://github.com/eventmachine/eventmachine/issues/724

Avoid warning about EventMachine.epoll / kqueue on JRuby

---

.travis.yml
Gemfile
Gemfile.lock
Rakefile

Mark those considered to be experimental under allowed_failures in Travis. 
Also moves server deps under bundle group in Gemfile and only runs client tests by default in CI env.

Add more rubies and jruby to Travis build

---

.travis.yml
Rakefile
lib/nats/client.rb
spec/client/attack_spec.rb
spec/client/auth_spec.rb
spec/client/autounsub_spec.rb
spec/client/binary_msg_spec.rb
spec/client/client_cluster_config_spec.rb
spec/client/client_cluster_reconnect_spec.rb
spec/client/client_config_spec.rb
spec/client/client_spec.rb
spec/client/client_tls_spec.rb
spec/client/cluster_lb_spec.rb
spec/client/cluster_multi_route_spec.rb
spec/client/cluster_retry_connect_spec.rb
spec/client/cluster_spec.rb
spec/client/error_on_client_spec.rb
spec/client/fast_producer_spec.rb
spec/client/queues_spec.rb
spec/client/reconnect_spec.rb
spec/client/server_info_spec.rb
spec/client/sub_timeouts_spec.rb
spec/spec_helper.rb

- Adds testing Java 7 and Java 8 under oraclejdk and openjdk
- Skip specs which generate inboxes in jruby, pending for now since low performant in CI environment (https://github.com/jruby/jruby/issues/3351)
- Also skip TLS specs in jruby since failing and need more tweaks :/
- Updates usage of rspec throughout
- Add profiling of tests to rspec to detect slow tests

Add more jruby versions to Travis build

---

.travis.yml
Gemfile.lock
lib/nats/client.rb
lib/nats/server/util.rb
lib/nats/version.rb
scripts/install_gnatsd.sh
spec/client/client_cluster_reconnect_spec.rb
spec/client/client_spec.rb
spec/client/cluster_auto_discovery_spec.rb
spec/client/cluster_retry_connect_spec.rb

- Implements cluster auto discovery which 0.9.2 server now supports
- Bumps gem to 0.8.0 major version

Cluster discovery via server info

---

bin/nats-pub
bin/nats-queue
bin/nats-request
bin/nats-sub
lib/nats/client.rb
spec/client/client_spec.rb

So that it shows up in monitoring endpoint, also minor cleanup from `bin/scripts`

Add optional for setting name from client

---

.travis.yml
Gemfile.lock
nats.gemspec

Also add pure ruby Eventmachine to the test matrix
Fixes #133

Update Eventmachine deps

---

.travis.yml
lib/nats/client.rb
spec/client/client_cluster_config_spec.rb
spec/client/client_tls_spec.rb
spec/client/reconnect_spec.rb

Current logic can make the client try to reconnect nonstop very fast until exhausting reconnect attempts when there are exceptions during when trying to establish a connections.
Fixes #138

Add Time based reconnect backoff

---

lib/nats/client.rb
spec/client/client_spec.rb
spec/spec_helper.rb

In order to test our Datadog Integration with gnatsd - we need to be able to control the name of the connection from the `nats-sub` and `nats-pub` CLI tools.  In keeping with the rest of the options, we've made that configurable via an ENV var.

Control Nats Connection Name via ENV var

---

Gemfile.lock
README.md
examples/fiber_request.rb
lib/nats/client.rb
lib/nats/nuid.rb
lib/nats/version.rb
nats.gemspec
spec/client/client_cluster_reconnect_spec.rb
spec/client/client_requests_spec.rb
spec/client/client_spec.rb
spec/client/nuid_spec.rb
spec/client/server_info_spec.rb

- Add new Fiber-aware `request` that works synchronously under the same fiber, using the new request/response implementation that is  less chatty over the network and uses a single async subscription.
- Introduce NUID style inboxes for requests
- Spec updates

New Request/Response implementation using Fibers

---

lib/nats/client.rb
spec/client/client_connect_spec.rb
spec/client/client_drain_spec.rb
spec/client/client_requests_spec.rb

Adds new `drain` API which a client can use to close a connection gracefully, allowing subscribers to process pending messages that have already been delivered by the server, done by announcing first to the server that no longer interested in receiving messages in all the subscriptions.
Unlike the Go client, it is only possible to drain the full connection since current implementation relies on a single buffer for all the subscriptions.
```ruby
NATS.start(drain_timeout: 1) do |nc|
NATS.subscribe('foo', queue: "workers") do |msg, reply, sub|
nc.publish(reply, "ACK:#{msg}")
end
NATS.subscribe('bar', queue: "workers") do |msg, reply, sub|
nc.publish(reply, "ACK:#{msg}")
end
NATS.subscribe('quux', queue: "workers") do |msg, reply, sub|
nc.publish(reply, "ACK:#{msg}")
end
EM.add_timer(2) do …
```

Support for Drain mode

---

Gemfile.lock
lib/nats/client.rb
lib/nats/version.rb
spec/client/client_spec.rb

Adds a simple helper to get inbound/outbound stats from the client similar to the Go client.
```ruby
NATS.start("demo.nats.io") do |nats|
nats.subscribe("foo") {
p nats.stats
}
nats.publish("foo", "world")
end
```
Signed-off-by: Waldemar Quevedo <wally@synadia.com>

Add method to get snapshot of in/out msgs/bytes stats
